2025-03-01T09:43:05.048Z - Backend error: Traceback (most recent call last):
  File "/home/zombie/ailinux/backend/app.py", line 10, in <module>
2025-03-01T09:43:05.049Z - Backend error: from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'
